automated update of desc-python:bleed on push to master
LSSTDESC/gcr-catalogs pull request #556
Opened 2021-01-22 20:08 UTC by heather999

fix #555
Think this will cause 2 workflows to run for every push to master on gcr-catalogs.  The first will update the desc-python:bleed docker image and the second will update desc-python:latest.  Not sure how to test other than just letting it run!

2021-01-22 20:35 UTC, yymao commented
Thanks @heather999. I temporarily added `pull_request` as a trigger for testing purpose. We should remove it later. 

Right now the workflow doesn't run. I think `matrix` variables cannot be used inside `include` options. See https://github.com/LSSTDESC/gcr-catalogs/actions/runs/504581903

2021-01-22 20:37 UTC, yymao requested changes
Matrix options cannot be used inside `include`. We can promote the full `docker_name`, `docker_image`, and `docker_image_updated` to matrix options.

2021-01-22 22:46 UTC, heather999 commented
I see the failure but not understanding the fix.  Is the suggestion to do?
```
strategy:
      matrix:
       desc_image_ver: [bleed, latest]
       docker_name: [updateGCR-bleed, updateGCR-latest]
       docker_image: [lsstdesc/desc-python:bleed, lsstdesc/desc-python:latest] 
       docker_image_updated: [lsstdesc/desc-python:bleed, lsstdesc/desc-python:latest]       
       include:
```         
But wouldn't that create 2x2x2x2 jobs?

2021-01-22 23:03 UTC, yymao commented
You're right. I guess we'll need to put them as two include items:

```yaml
       include:
         - docker_name: updateGCR-bleed
           docker_image: lsstdesc/desc-python:bleed
           docker_image_updated: lsstdesc/desc-python:bleed
           conda_activate: "conda activate desc;"
           setup_script: /usr/local/py3.7/etc/profile.d/conda.sh
         - docker_name: updateGCR-latest
           docker_image: lsstdesc/desc-python:latest
           docker_image_updated: lsstdesc/desc-python:latest
           conda_activate: "conda activate desc;"
           setup_script: /usr/local/py3.7/etc/profile.d/conda.sh
```

If we won't be enabling the stack one, we can clean up some of these (e.g., reduce `docker_image_updated`); otherwise this seems to be the only way to go?

2021-01-22 23:19 UTC, heather999 commented
Maybe?

```
      matrix:
       desc_image_ver: [lsstdesc/desc-python:bleed, lsstdesc/desc-python:latest]
       include:
         - conda_activate: "conda activate desc;"
           setup_script: /usr/local/py3.7/etc/profile.d/conda.sh

    steps:
      - name: docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: docker pull ${{ matrix.docker_image }}
      - name: Install master branch of ${{ github.repository }}
        run: docker run --name=updateGCR-${{ matrix.desc_image }} ${{ matrix.desc_image }} /bin/bash -c "source ${{ matrix.setup_script }}; ${{ matrix.conda_activate }} pip install https://github.com/${{ github.repository }}/archive/master.zip"
      - run: docker commit -m="Installed ${{ github.repository }} master" updateGCR-${{ matrix.desc_image }} ${{ matrix.desc_image }}
      - run: docker push ${{ matrix.desc_image }}
   ```

2021-01-23 00:20 UTC, yymao commented
How about the following? If we later want to recover the stack build, we can create a new step with `if: matrix.image_version == 'stack'` and set the variable differently?  

```yaml
    env:
       TARBALL_URL: https://github.com/${{ github.repository }}/archive/master.zip
    matrix:
       image_version: [bleed, latest]
    steps:
      - name: docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: set environment variables for bleed/latest
        if: matrix.image_version == 'bleed' || matrix.image_version == 'latest'
        run: |
          echo "DOCKER_NAME=updateGCR-${{ matrix.image_version }}" >> $GITHUB_ENV
          echo "IMAGE_NAME=lsstdesc/desc-python:${{ matrix.image_version }}" >> $GITHUB_ENV
          echo "CONDA_ACTIVATE='conda activate desc;'" >> $GITHUB_ENV
          echo "SETUP_SCRIPT=/usr/local/py3.7/etc/profile.d/conda.sh" >> $GITHUB_ENV
      - run: docker pull "$IMAGE_NAME"
      - name: Install master branch of ${{ github.repository }}
        run: docker run --name=$DOCKER_NAME $IMAGE_NAME /bin/bash -c "source $SETUP_SCRIPT; $CONDA_ACTIVATE pip install $TARBALL_URL"
      - run: docker commit -m="Installed ${{ github.repository }} master" $DOCKER_NAME $IMAGE_NAME
      - run: docker push $IMAGE_NAME
```

2021-01-25 17:49 UTC, heather999 commented
sorry wandered away for the weekend.. :)  Sure that sounds good.  I'll update the workflow and also add in a test so that obviously bad images aren't pushed.

2021-01-25 18:43 UTC, heather999 commented
test includes importing both GCRCatalogs as well as pyccl, because sometimes, making modifications to a docker image causes pyccl to fail.  It would be nice to catch that before pushing to dockerhub.

2021-01-25 18:50 UTC, yymao commented
sorry, there's an indentation error in my earlier suggestion. `env` and `steps` should be at the same level as `strategy`, and `matrix` should be nested inside `strategy`
```yaml    
    env:
      TARBALL_URL: https://github.com/${{ github.repository }}/archive/master.zip  
    strategy:
      matrix:
         image_version: [bleed, latest]
    steps:
```

2021-01-25 18:57 UTC, yymao commented on .github/workflows/desc-env-test.yml
> +        image_version: [bleed, latest]
`matrix` needs to be inside `strategy`, but `env` should be outside
```yaml 
    env:
      TARBALL_URL: https://github.com/${{ github.repository }}/archive/master.zip
    strategy:
      matrix:
        image_version: [bleed, latest]
```

2021-01-26 21:04 UTC, yymao approved these changes
OK, this turns out to be a lot more difficult than I thought :slightly_smiling_face: 

I think I finally have successful runs [here](https://github.com/LSSTDESC/gcr-catalogs/runs/1772331110?check_suite_focus=true) and [here](https://github.com/LSSTDESC/gcr-catalogs/runs/1772331124?check_suite_focus=true). 

@heather999 Can you confirm that the docker images on the docker host are indeed updated?

2021-01-26 22:01 UTC, heather999 commented
Great!  I can see both images have been updated on Dockerhub. They start up just fine.  Not sure if there's a good way to check that I have the latest master of gcr-catalogs, but this looks good enough to me.
My thought is to set up cron job at NERSC that will run a couple of times a day to grab the most recent bleed image and install it into shifter.

2021-01-26 22:28 UTC, yymao commented
Sounds good to me. Thanks! Merge at your leisure.

2021-01-26 22:32 UTC, merged