Issues/561/wfdphotozreader
LSSTDESC/gcr-catalogs pull request #564
Opened 2021-02-20 01:44 UTC by sschmidt23

This PR addresses issue #561 to add a reader for run2.2i_dr6_v2 photo-z catalog for BPZ.  I did a quick check and things seem to work properly for grabbing both mag_i_cModel and photoz_mode, @yymao you might want to look at the parameters that I set in dc2_object_run2.2i_dr6_v2_with_addons.yaml and make sure that I made the proper choices.

2021-02-20 16:00 UTC, yymao requested changes
Thanks @sschmidt23. I made a suggestion to remove one unnecessary option. 

Do we expect people to access only the photo-z catalog itself, and not as part of the composite? If we do, that's fine.  If not, should we remove `photoz_dc2_object_run2.2i_dr6_v2.yaml`?

2021-02-20 22:10 UTC, sschmidt23 commented on GCRCatalogs/catalog_configs/dc2_object_run2.2i_dr6_v2_with_addons.yaml
> +    as_object_addon: true
removed

2021-02-20 22:11 UTC, sschmidt23 commented
That's a good point, I don't see many people accessing the photo-z's without any sort of ties to the photometry or positions, so I think we can remove the standalone catalog.  I deleted the yaml file from the commit.

2021-02-21 15:18 UTC, yymao approved these changes
Thanks, @sschmidt23

2021-02-21 21:17 UTC, heather999 commented
Just a quick question - are these PZ strictly for internal DESC use with DR6 or are these PZs also meant for public release?

2021-02-21 21:50 UTC, sschmidt23 commented
For now they are for internal release, but I made the reader in case they end up being the public release candidate.  Johann and Alex were chatting about a potential alternative candidate for public release candidate, but it's never actually been run before.  So, I wanted to prepare this set as a backup and make sure that it functioned.  It should be useful internally no matter what.

2021-02-21 21:50 UTC, merged