Changes for switching to treecorr convention for position_angle
LSSTDESC/gcr-catalogs pull request #608
Opened 2022-11-28 22:44 UTC by evevkovacs

Legacy quantities have been renamed with _dc2. position_angle_true now uses morphology/position_angle and flips the sign to be consistent with the treecorr convention.
ellipticity_1* and ellipticity_2* now use the supplied values of morphology/position_angle and convert to the treecorrr convention before computing the components.

2022-11-28 23:01 UTC, jchiang87 submitted a review, later dismissed
Thanks, Eve!  lgtm.

2022-11-28 23:39 UTC, evevkovacs commented
@yymao @heather999 The above integration checks are failing. The first one is failing to load python 3.6! (Aren't we using 3.9?) And the remianing 2 checks are being cancelled. I need some help to resolve these issues. Thanks.

2022-11-29 01:06 UTC, yymao commented
Thanks @evevkovacs.  I'm fixing the action in #609. In the meantime can you update the [schema file](https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/SCHEMA.md) accordingly and include it in this PR?

2022-11-29 01:06 UTC, yymao requested changes
Update [schema file](https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/SCHEMA.md)

2022-11-30 23:58 UTC, evevkovacs commented
@yymao schema has been updated; checks have passed

2022-12-01 00:33 UTC, yymao approved these changes
Thanks @evevkovacs

2022-12-01 16:07 UTC, merged